import { type NextPage } from "next";
import Head from "next/head";


const ProfilePage: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div className=" w-full md:max-w-2xl border-x h-screen border-slate-400">
        </div>
      </main>
    </>
  );
};

export default ProfilePage;
